on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

name: test

defaults:
  run:
    shell: bash
    working-directory: go/src/github.com/frozzare/go

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.18
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: go/src/github.com/frozzare/go
    - name: Install
      run: |
        go mod verify
        go mod download
    - name: Test
      run: |
        go test ./...
        go vet ./...