on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

name: test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: src/github.com/frozzare/go
    - name: Debug
      run: |
        echo $GITHUB_WORKSPACE
        pwd
        ls -la .
        ls -la go/src/github.com/frozzare/go
    - name: Install
      run: |
        go mod verify
        go mod download
      working-directory: go/src/github.com/frozzare/go
    - name: Test
      run: |
        go test ./...
        go vet ./...
      working-directory: go/src/github.com/frozzare/go